apiVersion: v1
kind: Service
metadata:
  name: cxp-hello
  labels:
    app.kubernetes.io/name: cxp-hello
    app.kubernetes.io/instance: cxp-hello
    app.kubernetes.io/version: "0.8.0.LOCAL.1234567"
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cxp-hello
    app.kubernetes.io/instance: cxp-hello
