apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cxp-hello-helm.fullname" . }}
  labels:
    {{- include "cxp-hello-helm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cxp-hello-helm.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
