{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cxp-hello-helm.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "cxp-hello-helm.selectorLabels" . | nindent 6 }}
{{- end }}